import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import { db, initDatabase, seedDemo, demoBusinessId, transaction } from "./database/db.js";
import { calculatePulseScore } from "./services/pulseCalculator.js";
import { runForecastingAgent } from "./agents/forecastingAgent.js";
import { runCollectionsAgent } from "./agents/collectionsAgent.js";
import { runRiskAgent } from "./agents/riskAgent.js";
import { runAdvisorAgent } from "./agents/advisorAgent.js";

dotenv.config(); initDatabase(); seedDemo();
const app = express(), secret = process.env.JWT_SECRET || "finpilot-demo-secret";
app.use(cors({ origin: true, credentials: true })); app.use(express.json({ limit: "2mb" }));
const bid = (r) => r.user?.businessId || demoBusinessId();
const auth = (r,_s,n) => { const t=r.headers.authorization?.replace("Bearer ",""); if(t) try { r.user=jwt.verify(t,secret); } catch {} n(); };
const makeId = (p) => `${p}-${Date.now().toString().slice(-8)}`;
function data(businessId) {
  const business=db.prepare("SELECT name,industry,currency,bank_balance bankBalance,owner,gstin,since FROM businesses WHERE id=?").get(businessId);
  const invoices=db.prepare("SELECT id,customer,amount,issue_date issueDate,due_date dueDate,status,paid_date paidDate,days_overdue daysOverdue,risk,payment_delay_days paymentDelayDays,payment_history paymentHistory FROM invoices WHERE business_id=? ORDER BY issue_date DESC").all(businessId).map(x=>({...x,paymentHistory:JSON.parse(x.paymentHistory||"[]")}));
  const expenses=db.prepare("SELECT id,date,merchant,category,amount,description,recurring,risk FROM expenses WHERE business_id=? ORDER BY date DESC").all(businessId).map(x=>({...x,recurring:!!x.recurring}));
  const subscriptions=db.prepare("SELECT id,name,amount,billing_cycle billingCycle,last_used lastUsed,status,risk,description,potential_saving potentialSaving FROM subscriptions WHERE business_id=?").all(businessId);
  return {business,invoices,expenses,subscriptions};
}
app.get("/api/health",(_q,s)=>{try{db.prepare("SELECT 1").get();s.json({status:"ok",database:"connected"});}catch{s.status(500).json({error:"Database unavailable"});}});
app.post("/api/auth/register",(r,s)=>{const {businessName,ownerName,mobile,email="",password}=r.body||{};if(!businessName?.trim()||!ownerName?.trim()||!mobile?.trim()||!password||password.length<6)return s.status(400).json({error:"Business name, owner, mobile and a 6-character password are required"});if(db.prepare("SELECT id FROM users WHERE mobile=? OR (email<>'' AND email=?)").get(mobile.trim(),email.trim().toLowerCase()))return s.status(409).json({error:"An account with this mobile or email already exists"});const create=transaction(()=>{const b=db.prepare("INSERT INTO businesses(name,owner,bank_balance) VALUES (?,?,0)").run(businessName.trim(),ownerName.trim());return db.prepare("INSERT INTO users(business_id,owner_name,mobile,email,password_hash) VALUES (?,?,?,?,?)").run(b.lastInsertRowid,ownerName.trim(),mobile.trim(),email.trim().toLowerCase(),bcrypt.hashSync(password,10));});const u=db.prepare("SELECT * FROM users WHERE id=?").get(create.lastInsertRowid);s.status(201).json({token:jwt.sign({userId:u.id,businessId:u.business_id},secret,{expiresIn:"7d"}),user:{businessName,ownerName,mobile:u.mobile,email:u.email}});});
app.post("/api/auth/login",(r,s)=>{const {identifier,password}=r.body||{};const u=db.prepare("SELECT u.*,b.name businessName FROM users u JOIN businesses b ON b.id=u.business_id WHERE u.mobile=? OR lower(u.email)=lower(?)").get(identifier?.trim(),identifier?.trim());if(!u||!bcrypt.compareSync(password||"",u.password_hash))return s.status(401).json({error:"Incorrect credentials"});s.json({token:jwt.sign({userId:u.id,businessId:u.business_id},secret,{expiresIn:"7d"}),user:{businessName:u.businessName,ownerName:u.owner_name,mobile:u.mobile,email:u.email}});});
app.get("/api/auth/me",auth,(r,s)=>{if(!r.user)return s.status(401).json({error:"Authentication required"});const u=db.prepare("SELECT u.*,b.name businessName FROM users u JOIN businesses b ON b.id=u.business_id WHERE u.id=?").get(r.user.userId);s.json({user:{businessName:u.businessName,ownerName:u.owner_name,mobile:u.mobile,email:u.email}});});
app.get("/api/data",auth,(r,s)=>s.json(data(bid(r))));
app.get("/api/invoices",auth,(r,s)=>s.json(data(bid(r)).invoices));
app.post("/api/invoices",auth,(r,s)=>{const x=r.body||{};if(!x.customer||!Number(x.amount))return s.status(400).json({error:"Customer and amount are required"});const a={id:x.id||makeId("INV"),businessId:bid(r),customer:x.customer,amount:+x.amount,issueDate:x.issueDate||new Date().toISOString().slice(0,10),dueDate:x.dueDate||new Date().toISOString().slice(0,10),status:x.status||"PENDING",paidDate:x.paidDate||null,daysOverdue:+x.daysOverdue||0,risk:x.risk||"LOW",paymentDelayDays:x.paymentDelayDays||null,paymentHistory:JSON.stringify(x.paymentHistory||[])};db.prepare("INSERT INTO invoices VALUES (@id,@businessId,@customer,@amount,@issueDate,@dueDate,@status,@paidDate,@daysOverdue,@risk,@paymentDelayDays,@paymentHistory)").run(a);s.status(201).json({...a,paymentHistory:JSON.parse(a.paymentHistory)});});
function updateInvoice(r,s){const x=r.body||{},q=db.prepare("UPDATE invoices SET customer=?,amount=?,issue_date=?,due_date=?,status=?,paid_date=?,days_overdue=?,risk=?,payment_delay_days=?,payment_history=? WHERE id=? AND business_id=?").run(x.customer,+x.amount,x.issueDate,x.dueDate,x.status,x.paidDate||null,+x.daysOverdue||0,x.risk||"LOW",x.paymentDelayDays||null,JSON.stringify(x.paymentHistory||[]),r.params.id,bid(r));if(!q.changes)return s.status(404).json({error:"Invoice not found"});s.json(x);}
app.put("/api/invoices/:id",auth,updateInvoice);app.patch("/api/invoices/:id",auth,(r,s)=>{const old=data(bid(r)).invoices.find(x=>x.id===r.params.id);if(!old)return s.status(404).json({error:"Invoice not found"});r.body={...old,...r.body};updateInvoice(r,s);});
app.post("/api/invoices/:id/pay",auth,(r,s)=>{const b=bid(r),x=db.prepare("SELECT * FROM invoices WHERE id=? AND business_id=?").get(r.params.id,b);if(!x)return s.status(404).json({error:"Invoice not found"});const today=new Date().toISOString().slice(0,10);transaction(()=>{db.prepare("UPDATE invoices SET status='PAID',paid_date=?,days_overdue=0 WHERE id=?").run(today,x.id);db.prepare("UPDATE businesses SET bank_balance=bank_balance+? WHERE id=?").run(x.amount,b);db.prepare("INSERT INTO invoice_payment_history(invoice_id,amount,days_late,paid_at) VALUES(?,?,?,?)").run(x.id,x.amount,x.days_overdue,today);});s.json(data(b).invoices.find(i=>i.id===x.id));});
app.delete("/api/invoices/:id",auth,(r,s)=>{if(!db.prepare("DELETE FROM invoices WHERE id=? AND business_id=?").run(r.params.id,bid(r)).changes)return s.status(404).json({error:"Invoice not found"});s.status(204).end();});
app.get("/api/expenses",auth,(r,s)=>s.json(data(bid(r)).expenses));
app.post("/api/expenses",auth,(r,s)=>{const x=r.body||{};if(!x.merchant||!Number(x.amount))return s.status(400).json({error:"Merchant and amount are required"});const a={id:x.id||makeId("EXP"),businessId:bid(r),date:x.date||new Date().toISOString().slice(0,10),merchant:x.merchant,category:x.category||"Operations",amount:+x.amount,description:x.description||x.merchant,recurring:x.recurring?1:0,risk:x.risk||"LOW"};db.prepare("INSERT INTO expenses VALUES (@id,@businessId,@date,@merchant,@category,@amount,@description,@recurring,@risk)").run(a);s.status(201).json({...a,recurring:!!a.recurring});});
app.put("/api/expenses/:id",auth,(r,s)=>{const x=r.body||{},q=db.prepare("UPDATE expenses SET date=?,merchant=?,category=?,amount=?,description=?,recurring=?,risk=? WHERE id=? AND business_id=?").run(x.date,x.merchant,x.category,+x.amount,x.description,x.recurring?1:0,x.risk||"LOW",r.params.id,bid(r));if(!q.changes)return s.status(404).json({error:"Expense not found"});s.json(x);});app.delete("/api/expenses/:id",auth,(r,s)=>{if(!db.prepare("DELETE FROM expenses WHERE id=? AND business_id=?").run(r.params.id,bid(r)).changes)return s.status(404).json({error:"Expense not found"});s.status(204).end();});
app.get("/api/subscriptions",auth,(r,s)=>s.json(data(bid(r)).subscriptions));
app.get("/api/pulse",auth,(r,s)=>{const d=data(bid(r)),p=calculatePulseScore(d);s.json({...p,explanation:`Your pulse is ${p.status.toLowerCase()}. ₹${p.metrics.overdueTotal.toLocaleString("en-IN")} is tied up in overdue invoices, so collections are the fastest improvement.`});});
app.get("/api/cash-flow",auth,(r,s)=>{const d=data(bid(r));s.json({bankBalance:d.business.bankBalance,overdueTotal:d.invoices.filter(x=>x.status==="OVERDUE").reduce((a,x)=>a+x.amount,0),pendingTotal:d.invoices.filter(x=>x.status==="PENDING").reduce((a,x)=>a+x.amount,0),monthlyRecurringExpenses:d.expenses.filter(x=>x.recurring).reduce((a,x)=>a+x.amount,0)});});
app.get("/api/imports",auth,(r,s)=>s.json(db.prepare("SELECT id,filename,data_type dataType,count,imported_at importedAt FROM import_batches WHERE business_id=? ORDER BY imported_at DESC").all(bid(r))));app.post("/api/imports",auth,(r,s)=>{const x=r.body||{};if(!x.filename||!x.dataType)return s.status(400).json({error:"Filename and data type are required"});const a={id:x.id||makeId("batch"),businessId:bid(r),filename:x.filename,dataType:x.dataType,count:+x.count||0,importedAt:new Date().toISOString()};db.prepare("INSERT INTO import_batches VALUES (@id,@businessId,@filename,@dataType,@count,@importedAt)").run(a);s.status(201).json(a);});app.delete("/api/imports/:id",auth,(r,s)=>{db.prepare("DELETE FROM import_batches WHERE id=? AND business_id=?").run(r.params.id,bid(r));s.status(204).end();});
app.get("/api/bank",auth,(r,s)=>s.json(db.prepare("SELECT bank_name bankName,account_masked accountMasked,account_type accountType,balance,connected_at connectedAt,tx_count txCount,tx_volume txVolume,status FROM bank_connections WHERE business_id=?").get(bid(r))||null));app.post("/api/bank/connect",auth,(r,s)=>{const x=r.body||{},a={businessId:bid(r),bankName:x.bankName||"HDFC Bank",accountMasked:x.accountMasked||"•••• 4821",accountType:x.accountType||"Current Account",balance:+x.balance||480000,connectedAt:new Date().toISOString(),txCount:+x.txCount||248,txVolume:+x.txVolume||0};db.prepare("INSERT INTO bank_connections(business_id,bank_name,account_masked,account_type,balance,connected_at,tx_count,tx_volume) VALUES (@businessId,@bankName,@accountMasked,@accountType,@balance,@connectedAt,@txCount,@txVolume) ON CONFLICT(business_id) DO UPDATE SET bank_name=excluded.bank_name,account_masked=excluded.account_masked,account_type=excluded.account_type,balance=excluded.balance,connected_at=excluded.connected_at,tx_count=excluded.tx_count,tx_volume=excluded.tx_volume").run(a);db.prepare("UPDATE businesses SET bank_balance=? WHERE id=?").run(a.balance,a.businessId);s.json(a);});app.delete("/api/bank",auth,(r,s)=>{db.prepare("DELETE FROM bank_connections WHERE business_id=?").run(bid(r));s.status(204).end();});
app.post("/api/agents/run",auth,async(r,s)=>{const startedAt=new Date().toISOString();try{const d=data(bid(r)),forecasting=await runForecastingAgent(d).catch(()=>null),collections=await runCollectionsAgent(d).catch(()=>null),risk=await runRiskAgent(d).catch(()=>null),advisor=await runAdvisorAgent({forecasting,collections,risk}).catch(()=>null);s.json({success:true,agents:{forecasting,collections,risk,advisor},execution:{startedAt,completedAt:new Date().toISOString()}});}catch{s.status(500).json({error:"Agent execution failed"});}});
app.post("/api/assistant",auth,(r,s)=>{const d=data(bid(r)),q=String(r.body?.message||"").toLowerCase(),over=d.invoices.filter(x=>x.status==="OVERDUE"),total=over.reduce((a,x)=>a+x.amount,0);let response=`You have ₹${d.business.bankBalance.toLocaleString("en-IN")} in the bank.`,suggestedAction={label:"View dashboard",href:"/dashboard"};if(/ravi/.test(q)){const x=d.invoices.find(x=>x.customer.toLowerCase().includes("ravi")&&x.status!=="PAID");response=x?`Ravi Traders owes ₹${x.amount.toLocaleString("en-IN")} and is ${x.daysOverdue} days overdue.`:"Ravi Traders has no outstanding invoices.";suggestedAction={label:"View invoices",href:"/invoices"};}else if(/owe|overdue|unpaid|collect/.test(q)){response=`${over.length} customers owe ₹${total.toLocaleString("en-IN")}. ${over.map(x=>x.customer).slice(0,3).join(", ")} need follow-up.`;suggestedAction={label:"View invoices",href:"/invoices"};}else if(/spend|expense|software|cloudsuite/.test(q)){response=`Software spending is ₹${d.expenses.filter(x=>x.category==="Software").reduce((a,x)=>a+x.amount,0).toLocaleString("en-IN")}. CloudSuite Pro may save ₹6,999/month.`;suggestedAction={label:"Review spending",href:"/expenses"};}else if(/health|pulse/.test(q)){const p=calculatePulseScore(d);response=`Your financial health score is ${p.score}/100 (${p.status}). Overdue collections of ₹${total.toLocaleString("en-IN")} are the key factor.`;}s.json({response,suggestedAction});});
app.post("/api/demo/reset",auth,(_r,s)=>{
  const demoId=demoBusinessId();
  transaction(()=>{
    db.prepare("DELETE FROM invoice_payment_history WHERE invoice_id IN (SELECT id FROM invoices WHERE business_id=?)").run(demoId);
    ["invoices","expenses","subscriptions","import_batches","bank_connections"].forEach(table=>db.prepare(`DELETE FROM ${table} WHERE business_id=?`).run(demoId));
    db.prepare("DELETE FROM businesses WHERE id=?").run(demoId);
  })();
  seedDemo(); s.json(data(demoBusinessId()));
});
app.use((e,_r,s,_n)=>{console.error(e);s.status(500).json({error:"Something went wrong"});});app.listen(process.env.PORT||3001,()=>console.log("FinPilot API running on :3001"));
